#!/usr/bin/env bash

if [[ "$SKIP_GIT_PUSH_HOOK" ]]; then exit 0; fi

set -e

if [[ -n "$(git status --short)" ]]; then
    git stash
    function unstash() {
        git reset --hard
        git stash pop
    }
    trap unstash EXIT
fi

make manifests generate test

git diff --exit-code --quiet || (git status && exit 1)
