#!/bin/bash

if [[ -n "$(git status --short)" ]]; then
    git stash
    function unstash() {
        git reset --hard
        git stash pop
    }
    trap unstash EXIT
fi

make manifests generate test

git diff --exit-code --quiet || (git status && exit 1)
