#!/usr/bin/env bash

if [[ "$SKIP_GIT_PUSH_HOOK" ]]; then exit 0; fi

set -e

if git status --short | grep -qv "??"; then
    git stash
    function unstash() {
        git reset --hard
        git stash pop
    }
    trap unstash EXIT
fi

make earthly manifests generate
./bin/earthly -P +all

git diff --exit-code --quiet || (git status && exit 1)
